version: '3'

# Agent Solution BI - Task Runner
# Modern task orchestration for FastAPI + SolidJS stack

env:
  VITE_API_URL: http://127.0.0.1:8000
  PYTHONPATH: "{{.ROOT_DIR}}/backend"

vars:
  BACKEND_DIR: "{{.ROOT_DIR}}/backend"
  FRONTEND_DIR: "{{.ROOT_DIR}}/frontend-solid"
  VENV_PYTHON: "{{.BACKEND_DIR}}/.venv/Scripts/python.exe"
  VENV_PIP: "{{.BACKEND_DIR}}/.venv/Scripts/pip.exe"
  VENV_UVICORN: "{{.BACKEND_DIR}}/.venv/Scripts/uvicorn.exe"

tasks:
  # ============================================
  # Main Tasks
  # ============================================

  default:
    desc: Show available tasks
    cmds:
      - task --list

  install:
    desc: Install all dependencies (backend + frontend)
    cmds:
      - task: install:backend
      - task: install:frontend
      - echo ""
      - echo "✓ All dependencies installed successfully!"

  dev:
    desc: Start development servers (backend + frontend)
    deps:
      - validate:env
    cmds:
      - task: clean:ports
      - echo ""
      - echo "🚀 Starting Agent Solution BI..."
      - echo "   Backend:  http://localhost:8000"
      - echo "   Frontend: http://localhost:3000"
      - echo "   API Docs: http://localhost:8000/docs"
      - echo ""
      - npm run dev

  # ============================================
  # Backend Tasks
  # ============================================

  install:backend:
    desc: Install Python dependencies
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - echo "📦 Installing backend dependencies..."
      - '{{.VENV_PYTHON}} -m pip install --upgrade pip'
      - '{{.VENV_PIP}} install -r requirements.txt'
      - echo "✓ Backend dependencies installed"

  dev:backend:
    desc: Start FastAPI backend only
    deps:
      - validate:env
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - echo "🚀 Starting backend on http://localhost:8000"
      - '{{.VENV_PYTHON}} -m uvicorn main:app --reload --host 127.0.0.1 --port 8000'

  test:backend:
    desc: Run backend tests
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - '{{.VENV_PYTHON}} -m pytest -v'

  lint:backend:
    desc: Lint backend code
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - '{{.VENV_PYTHON}} -m ruff check app/'

  format:backend:
    desc: Format backend code
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - '{{.VENV_PYTHON}} -m black app/'

  # ============================================
  # Frontend Tasks
  # ============================================

  install:frontend:
    desc: Install Node.js dependencies
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - echo "📦 Installing frontend dependencies..."
      - pnpm install
      - echo "✓ Frontend dependencies installed"

  dev:frontend:
    desc: Start SolidJS frontend only
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - echo "🚀 Starting frontend on http://localhost:3000"
      - pnpm dev

  build:frontend:
    desc: Build frontend for production
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - pnpm build

  # ============================================
  # Utility Tasks
  # ============================================

  clean:ports:
    desc: Kill processes on ports 8000 and 3000
    cmds:
      - echo "🧹 Cleaning ports 8000 and 3000..."
      - kill-port 8000 3000 || echo "✓ Ports already free"

  clean:cache:
    desc: Clean Python cache files
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - echo "🧹 Cleaning Python cache..."
      - powershell -Command "Get-ChildItem -Path . -Include __pycache__,*.pyc -Recurse -Force | Remove-Item -Recurse -Force"
      - echo "✓ Cache cleaned"

  validate:env:
    desc: Validate .env file exists
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - cmd: test -f .env
        platforms: [linux, darwin]
      - cmd: if not exist .env (echo ✗ backend/.env missing! && exit 1) else (echo ✓ backend/.env exists)
        platforms: [windows]

  health:
    desc: Check if services are running
    cmds:
      - echo "🏥 Health Check:"
      - cmd: curl -s http://localhost:8000/health || echo "✗ Backend not running"
        ignore_error: true
      - cmd: curl -s http://localhost:3000 || echo "✗ Frontend not running"
        ignore_error: true

  # ============================================
  # Database Tasks
  # ============================================

  db:migrate:
    desc: Run database migrations
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - '{{.VENV_PYTHON}} -m alembic upgrade head'

  db:revision:
    desc: Create new database migration
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - '{{.VENV_PYTHON}} -m alembic revision --autogenerate -m "{{.CLI_ARGS}}"'

  # ============================================
  # Production Tasks
  # ============================================

  prod:
    desc: Start production servers (requires PM2)
    cmds:
      - echo "🚀 Starting production servers..."
      - pm2 start ecosystem.config.js
      - echo "✓ Servers started. Use 'pm2 logs' to view logs"

  prod:stop:
    desc: Stop production servers
    cmds:
      - pm2 stop ecosystem.config.js

  prod:restart:
    desc: Restart production servers
    cmds:
      - pm2 restart ecosystem.config.js

  # ============================================
  # Setup Tasks
  # ============================================

  setup:
    desc: Initial project setup
    cmds:
      - echo "🔧 Setting up Agent Solution BI..."
      - task: setup:env
      - task: install
      - echo ""
      - echo "✓ Setup complete! Run 'task dev' to start"

  setup:env:
    desc: Create .env file from .env.example
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - cmd: test -f .env && echo "⚠️  .env already exists, skipping..." || cp .env.example .env
        platforms: [linux, darwin]
      - cmd: if exist .env (echo ⚠️  .env already exists, skipping...) else (copy .env.example .env)
        platforms: [windows]
